include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
