include: package:lints/recommended.yaml

linter:
  rules:
    public_member_api_docs: false
    file_names: false  # Dart Frog uses [param].dart for dynamic routes
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
