import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:offline_first_sync_drift/src/constants.dart';
import 'package:offline_first_sync_drift/src/cursor.dart';
import 'package:offline_first_sync_drift/src/internal/outbox_timestamp.dart';
import 'package:offline_first_sync_drift/src/op.dart';
import 'package:offline_first_sync_drift/src/tables/cursors.drift.dart';
import 'package:offline_first_sync_drift/src/tables/outbox.drift.dart';
import 'package:offline_first_sync_drift/src/tables/outbox_meta.drift.dart';
import 'package:offline_first_sync_drift/src/tables/sync_data_classes.dart';

/// Callback invoked after a successful, durable outbox enqueue for [kind].
///
/// Used by [SyncEngine] to wire the optional `pushOnEnqueue` debounce. The
/// callback is fired by [SyncEntityWriter] only after the enclosing local
/// write/transaction (if any) has committed, so it is safe to schedule
/// follow-up work that assumes the outbox row is durable.
typedef OnOutboxCommittedCallback = void Function(String kind);

/// SQLite builds before 3.32 accept at most 999 variables per statement.
const _maxSqlVariables = 500;

/// The indexes declared on `SyncOutbox`, as generated by drift.
List<Index> get _syncOutboxIndexes => [
  idxSyncOutboxKindTs,
  idxSyncOutboxTs,
  idxSyncOutboxKindEntity,
];

/// Mixin for databases with synchronization support.
///
/// Usage:
/// 1. Add to `@DriftDatabase`:
///    `include: {'package:offline_first_sync_drift/src/sync_tables.drift'}`
/// 2. Add `with SyncDatabaseMixin` to your database class.
///
/// Drift will automatically include the `sync_outbox` and `sync_cursors` tables.
mixin SyncDatabaseMixin on GeneratedDatabase {
  TableInfo<Table, SyncOutboxData>? _outboxTable;
  TableInfo<Table, SyncOutboxMetaData>? _outboxMetaTable;
  TableInfo<Table, SyncCursorData>? _cursorsTable;

  /// Optional hook invoked by [SyncEntityWriter] after a successful outbox
  /// enqueue (post-commit). Set by [SyncEngine] when `pushOnEnqueue` is
  /// enabled; otherwise null. Internal writer paths invoke it via
  /// [notifyOutboxCommitted]; do not call it from raw `db.enqueue(...)`.
  OnOutboxCommittedCallback? onOutboxCommitted;

  /// Internal: invoked by [SyncEntityWriter] after a durable enqueue. Safe to
  /// call when no hook is registered.
  void notifyOutboxCommitted(String kind) {
    final cb = onOutboxCommitted;
    if (cb == null) return;
    cb(kind);
  }

  /// Get outbox table.
  TableInfo<Table, SyncOutboxData> get _outbox => _outboxTable ??= allTables
      .whereType<TableInfo<Table, SyncOutboxData>>()
      .firstWhere(
        (t) => t.actualTableName == 'sync_outbox',
        orElse: () => throw StateError(
          'SyncOutbox table not found. Make sure to add:\n'
          "include: {'package:offline_first_sync_drift/src/sync_tables.drift'}\n"
          'to your @DriftDatabase annotation.',
        ),
      );

  /// Get cursors table.
  TableInfo<Table, SyncCursorData> get _cursors => _cursorsTable ??= allTables
      .whereType<TableInfo<Table, SyncCursorData>>()
      .firstWhere(
        (t) => t.actualTableName == 'sync_cursors',
        orElse: () => throw StateError(
          'SyncCursors table not found. Make sure to add:\n'
          "include: {'package:offline_first_sync_drift/src/sync_tables.drift'}\n"
          'to your @DriftDatabase annotation.',
        ),
      );

  /// Get outbox meta table.
  TableInfo<Table, SyncOutboxMetaData> get _outboxMeta => _outboxMetaTable ??=
      allTables.whereType<TableInfo<Table, SyncOutboxMetaData>>().firstWhere(
        (t) => t.actualTableName == TableNames.syncOutboxMeta,
        orElse: () => throw StateError(
          'SyncOutboxMeta table not found. Make sure to add:\n'
          "include: {'package:offline_first_sync_drift/src/sync_tables.drift'}\n"
          'to your @DriftDatabase annotation and run migrations.',
        ),
      );

  /// Creates the outbox indexes on a database that does not have them yet.
  ///
  /// New databases get them from `Migrator.createAll()`. A database that was
  /// created by an older version of this package has the `sync_outbox` table
  /// without them; every statement is `CREATE INDEX IF NOT EXISTS`, so calling
  /// this is safe at any time, any number of times, and next to a migration
  /// that creates the same indexes. [SyncEngine] calls it before its first
  /// sync; call it from `onUpgrade` if you verify your schema after
  /// migrations.
  Future<void> ensureSyncIndexes() async {
    for (final index in _syncOutboxIndexes) {
      for (final statement in index.createStatementsByDialect.values) {
        await customStatement(statement);
      }
    }
  }

  /// Add operation to the outbox queue.
  Future<void> enqueue(Op op) async {
    final ts = op.localTimestamp.toUtc().millisecondsSinceEpoch;

    if (op is UpsertOp) {
      final base = op.baseUpdatedAt;
      final baseTs = base == null ? null : encodeOutboxTimestamp(base);
      final changedFieldsJson = op.changedFields != null
          ? jsonEncode(op.changedFields!.toList())
          : null;

      await into(_outbox).insertOnConflictUpdate(
        SyncOutboxCompanion.insert(
          opId: op.opId,
          kind: op.kind,
          entityId: op.id,
          op: OpType.upsert,
          ts: ts,
          payload: Value(jsonEncode(op.payloadJson)),
          tryCount: const Value(0),
          baseUpdatedAt: Value(baseTs),
          changedFields: Value(changedFieldsJson),
        ),
      );
    } else if (op is DeleteOp) {
      final base = op.baseUpdatedAt;
      final baseTs = base == null ? null : encodeOutboxTimestamp(base);

      await into(_outbox).insertOnConflictUpdate(
        SyncOutboxCompanion.insert(
          opId: op.opId,
          kind: op.kind,
          entityId: op.id,
          op: OpType.delete,
          ts: ts,
          tryCount: const Value(0),
          baseUpdatedAt: Value(baseTs),
        ),
      );
    }
  }

  /// Get queued operations for sending.
  ///
  /// If [kinds] is provided, only operations for those entity kinds are returned.
  /// If [maxTryCountExclusive] is set, only operations with smaller tryCount
  /// are returned.
  Future<List<Op>> takeOutbox({
    int limit = 100,
    Set<String>? kinds,
    int? maxTryCountExclusive,
  }) async {
    final rows = await _selectOutboxRows(
      limit: limit,
      kinds: kinds,
      maxTryCountExclusive: maxTryCountExclusive,
    );
    return _rowsToOps(rows);
  }

  Future<List<QueryRow>> _selectOutboxRows({
    required int limit,
    Set<String>? kinds,
    int? maxTryCountExclusive,
  }) {
    final hasKindsFilter = kinds != null;
    final hasTryFilter = maxTryCountExclusive != null;
    if (hasKindsFilter && kinds.isEmpty) {
      return Future.value(const <QueryRow>[]);
    }

    final whereParts = <String>[];
    final variables = <Variable<Object>>[];

    if (hasKindsFilter) {
      final kindList = kinds.toList()..sort();
      final placeholders = List.filled(kindList.length, '?').join(', ');
      whereParts.add('${TableColumns.kind} IN ($placeholders)');
      variables.addAll(kindList.map(Variable.withString));
    }

    if (hasTryFilter) {
      whereParts.add('${TableColumns.tryCount} < ?');
      variables.add(Variable.withInt(maxTryCountExclusive));
    }

    final whereClause = whereParts.isEmpty
        ? ''
        : 'WHERE ${whereParts.join(' AND ')} ';
    variables.add(Variable.withInt(limit));

    return customSelect(
      'SELECT * FROM ${TableNames.syncOutbox} '
      '$whereClause'
      // `ts` has millisecond resolution; rowid keeps ops enqueued in the
      // same millisecond in insertion order instead of an arbitrary one.
      'ORDER BY ${TableColumns.ts}, rowid LIMIT ?',
      variables: variables,
      readsFrom: {_outbox},
    ).get();
  }

  /// Watch pending outbox count as a stream.
  Stream<int> watchOutboxCount({
    Set<String>? kinds,
    int? maxTryCountExclusive,
  }) {
    final hasKindsFilter = kinds != null;
    final hasTryFilter = maxTryCountExclusive != null;
    if (hasKindsFilter && kinds.isEmpty) {
      return Stream<int>.value(0);
    }

    final whereParts = <String>[];
    final variables = <Variable<Object>>[];

    if (hasKindsFilter) {
      final kindList = kinds.toList()..sort();
      final placeholders = List.filled(kindList.length, '?').join(', ');
      whereParts.add('${TableColumns.kind} IN ($placeholders)');
      variables.addAll(kindList.map(Variable.withString));
    }

    if (hasTryFilter) {
      whereParts.add('${TableColumns.tryCount} < ?');
      variables.add(Variable.withInt(maxTryCountExclusive));
    }

    final whereClause = whereParts.isEmpty
        ? ''
        : 'WHERE ${whereParts.join(' AND ')}';
    return customSelect(
      'SELECT COUNT(*) as c FROM ${TableNames.syncOutbox} $whereClause',
      variables: variables,
      readsFrom: {_outbox},
    ).watch().map((rows) => rows.first.read<int>('c'));
  }

  /// Watch stuck operations count.
  Stream<int> watchStuckOutboxCount({
    required int minTryCount,
    Set<String>? kinds,
  }) {
    final hasKindsFilter = kinds != null;
    if (hasKindsFilter && kinds.isEmpty) {
      return Stream<int>.value(0);
    }

    final whereParts = <String>['${TableColumns.tryCount} >= ?'];
    final variables = <Variable<Object>>[Variable.withInt(minTryCount)];

    if (hasKindsFilter) {
      final kindList = kinds.toList()..sort();
      final placeholders = List.filled(kindList.length, '?').join(', ');
      whereParts.add('${TableColumns.kind} IN ($placeholders)');
      variables.addAll(kindList.map(Variable.withString));
    }

    final whereClause = 'WHERE ${whereParts.join(' AND ')}';
    return customSelect(
      'SELECT COUNT(*) as c FROM ${TableNames.syncOutbox} $whereClause',
      variables: variables,
      readsFrom: {_outbox},
    ).watch().map((rows) => rows.first.read<int>('c'));
  }

  /// Increment try count for operations.
  Future<void> incrementOutboxTryCount(Iterable<String> opIds) async {
    if (opIds.isEmpty) return;
    final ids = opIds.toList();
    final placeholders = List.filled(ids.length, '?').join(', ');
    await customStatement(
      'UPDATE ${TableNames.syncOutbox} '
      'SET ${TableColumns.tryCount} = ${TableColumns.tryCount} + 1 '
      'WHERE ${TableColumns.opId} IN ($placeholders)',
      ids,
    );
  }

  /// Reset try count for operations.
  Future<void> resetOutboxTryCount(Iterable<String> opIds) async {
    if (opIds.isEmpty) return;
    final ids = opIds.toList();
    final placeholders = List.filled(ids.length, '?').join(', ');
    await customStatement(
      'UPDATE ${TableNames.syncOutbox} '
      'SET ${TableColumns.tryCount} = 0 '
      'WHERE ${TableColumns.opId} IN ($placeholders)',
      ids,
    );
  }

  /// Record outbox failures: increment tryCount and store last error metadata.
  Future<void> recordOutboxFailures(
    Map<String, String> errors, {
    DateTime? triedAt,
  }) async {
    if (errors.isEmpty) return;
    final ts = (triedAt ?? DateTime.now().toUtc()).millisecondsSinceEpoch;

    await transaction(() async {
      await incrementOutboxTryCount(errors.keys);

      try {
        await batch(
          (b) => b.insertAllOnConflictUpdate(_outboxMeta, [
            for (final MapEntry(key: opId, value: error) in errors.entries)
              SyncOutboxMetaCompanion.insert(
                opId: opId,
                lastTriedAt: Value(ts),
                lastError: Value(error),
              ),
          ]),
        );
      } catch (_) {
        // Metadata is optional; ignore if table is unavailable.
      }
    });
  }

  /// Remove outbox metadata for the specified operations.
  Future<void> deleteOutboxMeta(Iterable<String> opIds) async {
    if (opIds.isEmpty) return;
    final ids = opIds.toList();
    final placeholders = List.filled(ids.length, '?').join(', ');
    await customStatement(
      'DELETE FROM ${TableNames.syncOutboxMeta} '
      'WHERE ${TableColumns.opId} IN ($placeholders)',
      ids,
    );
  }

  /// Count stuck operations by try-count threshold.
  Future<int> countStuckOutbox({
    required int minTryCount,
    Set<String>? kinds,
  }) async {
    final hasKindsFilter = kinds != null;
    if (hasKindsFilter && kinds.isEmpty) return 0;

    final whereParts = <String>['${TableColumns.tryCount} >= ?'];
    final variables = <Variable<Object>>[Variable.withInt(minTryCount)];

    if (hasKindsFilter) {
      final kindList = kinds.toList()..sort();
      final placeholders = List.filled(kindList.length, '?').join(', ');
      whereParts.add('${TableColumns.kind} IN ($placeholders)');
      variables.addAll(kindList.map(Variable.withString));
    }

    final whereClause = 'WHERE ${whereParts.join(' AND ')}';
    final rows = await customSelect(
      'SELECT COUNT(*) as c FROM ${TableNames.syncOutbox} $whereClause',
      variables: variables,
      readsFrom: {_outbox},
    ).get();
    return rows.first.read<int>('c');
  }

  /// Get operations considered stuck by try-count threshold.
  Future<List<Op>> getStuckOutbox({
    required int minTryCount,
    int limit = 100,
    Set<String>? kinds,
  }) async {
    if (minTryCount <= 0) {
      throw ArgumentError.value(minTryCount, 'minTryCount', 'must be > 0');
    }
    final hasKindsFilter = kinds != null;
    if (hasKindsFilter && kinds.isEmpty) return const <Op>[];

    final whereParts = <String>['${TableColumns.tryCount} >= ?'];
    final variables = <Variable<Object>>[Variable.withInt(minTryCount)];

    if (hasKindsFilter) {
      final kindList = kinds.toList()..sort();
      final placeholders = List.filled(kindList.length, '?').join(', ');
      whereParts.add('${TableColumns.kind} IN ($placeholders)');
      variables.addAll(kindList.map(Variable.withString));
    }

    final whereClause = whereParts.join(' AND ');
    variables.add(Variable.withInt(limit));
    final rows = await customSelect(
      'SELECT * FROM ${TableNames.syncOutbox} '
      'WHERE $whereClause '
      'ORDER BY ${TableColumns.ts}, rowid LIMIT ?',
      variables: variables,
      readsFrom: {_outbox},
    ).get();
    return _rowsToOps(rows);
  }

  List<Op> _rowsToOps(List<QueryRow> rows) => rows.map((row) {
    final opId = row.read<String>(TableColumns.opId);
    final kind = row.read<String>(TableColumns.kind);
    final entityId = row.read<String>(TableColumns.entityId);
    final opType = row.read<String>(TableColumns.op);
    final tsMillis = row.read<int>(TableColumns.ts);
    final storedBase = row.readNullable<int>(TableColumns.baseUpdatedAt);

    final ts = DateTime.fromMillisecondsSinceEpoch(tsMillis, isUtc: true);
    final baseUpdatedAt = storedBase == null
        ? null
        : decodeOutboxTimestamp(storedBase);

    if (opType == OpType.delete) {
      return DeleteOp(
        opId: opId,
        kind: kind,
        id: entityId,
        localTimestamp: ts,
        baseUpdatedAt: baseUpdatedAt,
      );
    }

    final payloadStr = row.readNullable<String>(TableColumns.payload);
    final payload = payloadStr == null
        ? <String, Object?>{}
        : (jsonDecode(payloadStr) as Map<String, Object?>);
    final changedFieldsStr = row.readNullable<String>(
      TableColumns.changedFields,
    );
    Set<String>? changedFields;
    if (changedFieldsStr != null) {
      final list = jsonDecode(changedFieldsStr) as List<dynamic>;
      changedFields = list.cast<String>().toSet();
    }

    return UpsertOp(
      opId: opId,
      kind: kind,
      id: entityId,
      localTimestamp: ts,
      payloadJson: payload,
      baseUpdatedAt: baseUpdatedAt,
      changedFields: changedFields,
    );
  }).toList();

  /// Re-bases the queued ops of one entity onto [serverVersion].
  ///
  /// Call this when the server reports a new version of the entity (a
  /// successful push or a resolved conflict). Ops that were enqueued against
  /// the previous version would otherwise be pushed with a stale
  /// `_baseUpdatedAt` and be rejected as conflicts with our own write.
  ///
  /// Ops without a base keep none: a null base means "create, fail if it
  /// exists", and inventing one would change that meaning. Returns the number
  /// of re-based ops.
  Future<int> rebaseOutboxOps({
    required String kind,
    required String entityId,
    required DateTime serverVersion,
  }) => customUpdate(
    'UPDATE ${TableNames.syncOutbox} '
    'SET ${TableColumns.baseUpdatedAt} = ? '
    'WHERE ${TableColumns.kind} = ? AND ${TableColumns.entityId} = ? '
    'AND ${TableColumns.baseUpdatedAt} IS NOT NULL',
    variables: [
      Variable.withInt(encodeOutboxTimestamp(serverVersion)),
      Variable.withString(kind),
      Variable.withString(entityId),
    ],
    updates: {_outbox},
    updateKind: UpdateKind.update,
  );

  /// [rebaseOutboxOps] for many entities at once, keyed by `(kind, entity id)`.
  ///
  /// After a batch was pushed, almost none of its entities have further ops
  /// queued. One lookup per kind finds the few that do, and only those are
  /// updated — instead of one `UPDATE` per pushed op. Returns the number of
  /// re-based ops.
  Future<int> rebaseQueuedOutboxOps(
    Map<(String, String), DateTime> serverVersions,
  ) async {
    final idsByKind = <String, List<String>>{};
    for (final (kind, entityId) in serverVersions.keys) {
      (idsByKind[kind] ??= []).add(entityId);
    }

    var rebased = 0;
    for (final MapEntry(key: kind, value: ids) in idsByKind.entries) {
      for (var from = 0; from < ids.length; from += _maxSqlVariables) {
        final chunk = ids.skip(from).take(_maxSqlVariables).toList();
        final placeholders = List.filled(chunk.length, '?').join(', ');
        final queued = await customSelect(
          'SELECT DISTINCT ${TableColumns.entityId} '
          'FROM ${TableNames.syncOutbox} '
          'WHERE ${TableColumns.kind} = ? '
          'AND ${TableColumns.entityId} IN ($placeholders) '
          'AND ${TableColumns.baseUpdatedAt} IS NOT NULL',
          variables: [
            Variable.withString(kind),
            ...chunk.map(Variable.withString),
          ],
          readsFrom: {_outbox},
        ).get();

        for (final row in queued) {
          final entityId = row.read<String>(TableColumns.entityId);
          rebased += await rebaseOutboxOps(
            kind: kind,
            entityId: entityId,
            serverVersion: serverVersions[(kind, entityId)]!,
          );
        }
      }
    }
    return rebased;
  }

  /// Acknowledge sent operations (remove from queue).
  Future<void> ackOutbox(Iterable<String> opIds) async {
    if (opIds.isEmpty) return;
    final ids = opIds.toList();
    final placeholders = List.filled(ids.length, '?').join(', ');

    await customStatement(
      'DELETE FROM ${TableNames.syncOutbox} WHERE ${TableColumns.opId} IN ($placeholders)',
      ids,
    );

    // Best-effort cleanup for metadata.
    try {
      await customStatement(
        'DELETE FROM ${TableNames.syncOutboxMeta} '
        'WHERE ${TableColumns.opId} IN ($placeholders)',
        ids,
      );
    } catch (_) {}
  }

  /// Get cursor for an entity kind.
  Future<Cursor?> getCursor(String kind) async {
    final rows = await customSelect(
      'SELECT ${TableColumns.ts}, ${TableColumns.lastId} '
      'FROM ${TableNames.syncCursors} WHERE ${TableColumns.kind} = ?',
      variables: [Variable.withString(kind)],
      readsFrom: {_cursors},
    ).get();

    if (rows.isEmpty) return null;

    final row = rows.first;
    return Cursor(
      ts: DateTime.fromMillisecondsSinceEpoch(
        row.read<int>(TableColumns.ts),
        isUtc: true,
      ),
      lastId: row.read<String>(TableColumns.lastId),
    );
  }

  /// Save cursor for an entity kind.
  Future<void> setCursor(String kind, Cursor cursor) async {
    await into(_cursors).insertOnConflictUpdate(
      SyncCursorsCompanion.insert(
        kind: kind,
        ts: cursor.ts.toUtc().millisecondsSinceEpoch,
        lastId: cursor.lastId,
      ),
    );
  }

  /// Purge operations older than threshold.
  Future<int> purgeOutboxOlderThan(DateTime threshold) async {
    final th = threshold.toUtc().millisecondsSinceEpoch;
    return customUpdate(
      'DELETE FROM ${TableNames.syncOutbox} WHERE ${TableColumns.ts} <= ?',
      variables: [Variable.withInt(th)],
      updateKind: UpdateKind.delete,
    );
  }

  /// Reset all cursors for the specified kinds.
  Future<void> resetAllCursors(Set<String> kinds) async {
    if (kinds.isEmpty) return;

    final placeholders = List.filled(kinds.length, '?').join(', ');
    await customStatement(
      'DELETE FROM ${TableNames.syncCursors} WHERE ${TableColumns.kind} IN ($placeholders)',
      kinds.toList(),
    );
  }

  /// Clear data from syncable tables.
  /// [tableNames] - table names to clear.
  Future<void> clearSyncableTables(List<String> tableNames) async {
    for (final tableName in tableNames) {
      await customStatement('DELETE FROM "$tableName"');
    }
  }
}
