import 'package:json_annotation/json_annotation.dart';

part 'note.g.dart';

/// Note model for the frontend — the app's second synced kind.
///
/// Notes exist to show two things todos cannot show on their own: that one
/// sync engine carries several tables, and that each kind may settle
/// conflicts its own way. Todos ask the user; notes merge automatically.
///
/// Uses snake_case for JSON serialization to match backend API.
@JsonSerializable(fieldRename: FieldRename.snake)
class Note {
  Note({
    required this.id,
    required this.title,
    this.body,
    this.pinned = false,
    required this.updatedAt,
    this.deletedAt,
    this.deletedAtLocal,
  });

  factory Note.fromJson(Map<String, dynamic> json) => _$NoteFromJson(json);

  /// Unique identifier (UUID), generated by the client.
  final String id;

  /// Note title (required).
  final String title;

  /// Free-form body.
  final String? body;

  /// Whether the note is pinned to the top of the list.
  final bool pinned;

  /// Last update timestamp (set by server).
  final DateTime updatedAt;

  /// Soft delete timestamp from server.
  final DateTime? deletedAt;

  /// Local delete timestamp (before sync).
  final DateTime? deletedAtLocal;

  Map<String, dynamic> toJson() => _$NoteToJson(this);

  /// Creates a copy with updated fields.
  ///
  /// Like `Todo.copyWith` it cannot *clear* a nullable field; build the copy
  /// by hand when you need `body` to become null.
  Note copyWith({
    String? id,
    String? title,
    String? body,
    bool? pinned,
    DateTime? updatedAt,
    DateTime? deletedAt,
    DateTime? deletedAtLocal,
  }) {
    return Note(
      id: id ?? this.id,
      title: title ?? this.title,
      body: body ?? this.body,
      pinned: pinned ?? this.pinned,
      updatedAt: updatedAt ?? this.updatedAt,
      deletedAt: deletedAt ?? this.deletedAt,
      deletedAtLocal: deletedAtLocal ?? this.deletedAtLocal,
    );
  }

  @override
  String toString() => 'Note(id: $id, title: $title, pinned: $pinned)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          body == other.body &&
          pinned == other.pinned &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          deletedAtLocal == other.deletedAtLocal;

  @override
  int get hashCode => Object.hash(
    id,
    title,
    body,
    pinned,
    updatedAt,
    deletedAt,
    deletedAtLocal,
  );
}
