import 'package:drift/drift.dart';
import 'package:offline_first_sync_drift/offline_first_sync_drift.dart';

import '../../models/note.dart';

/// Drift table definition for notes.
///
/// Uses [SyncColumns] exactly like `Todos`: the sync engine needs
/// `updatedAt`, `deletedAt` and `deletedAtLocal` on every synced table.
@UseRowClass(Note, generateInsertable: true)
class Notes extends Table with SyncColumns {
  /// Unique identifier (UUID), generated by the client.
  TextColumn get id => text()();

  /// Note title (required).
  TextColumn get title => text().withLength(min: 1, max: 255)();

  /// Free-form body.
  TextColumn get body => text().nullable()();

  /// Whether the note is pinned to the top of the list.
  BoolColumn get pinned => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}
